apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: html-pvc
  labels:
    env: test
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: html-log-pvc
  labels:
    env: test
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

apiVersion: v1
kind: Service
metadata:
  name: html-svc
  labels:
    name: html-svc
spec:
  selector:
    name: html-pod
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32100
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-app
  labels:
    name: html-app
    env: test
spec:
  replicas: 1
  selector:
    matchExpressions:
    - { key: name, operator: In , values: [ html-pod ] }
  template:
    metadata:
      name: html-pod
      labels:
        name: html-pod
    spec:
      containers:
      - name: html-con
        image: raghav1674/html-6:v1
        volumeMounts:
        - name: html-log
          mountPath: /var/log/httpd/
        - name: html-dir
          mountPath: /var/www/html/
      volumes:
      - name: html-log
        persistentVolumeClaim:
          claimName: html-log-pvc
      - name: html-dir
        persistentVolumeClaim:
          claimName: html-pvc

